version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sampledb
    ports:
      - "3306:3306"
